## This configuration was generated by terraform-provider-oci

resource oci_core_instance export_FORTI-MASTER1 {
  agent_config {
    are_all_plugins_disabled = "false"
    is_management_disabled   = "false"
    is_monitoring_disabled   = "false"
    plugins_config {
      desired_state = "DISABLED"
      name          = "Vulnerability Scanning"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Oracle Autonomous Linux"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "OS Management Service Agent"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Management Agent"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "Custom Logs Monitoring"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "Compute Instance Run Command"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "Compute Instance Monitoring"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Block Volume Management"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Bastion"
    }
  }
  #async = <<Optional value not found in discovery>>
  availability_config {
    #is_live_migration_preferred = <<Optional value not found in discovery>>
    recovery_action = "RESTORE_INSTANCE"
  }
  availability_domain = data.oci_identity_availability_domain.export_IzXN-CA-TORONTO-1-AD-1.name
  #capacity_reservation_id = <<Optional value not found in discovery>>
  compartment_id = var.compartment_ocid
  create_vnic_details {
    #assign_private_dns_record = <<Optional value not found in discovery>>
    assign_public_ip = "true"
    defined_tags = {
      "Oracle-Tags.CreatedBy" = "azure_economieqc/apiroyer@economieqc.onmicrosoft.com"
      "Oracle-Tags.CreatedOn" = "2021-11-04T01:06:43.031Z"
    }
    display_name = "PORT1"
    freeform_tags = {
    }
    hostname_label = "forti-master1"
    nsg_ids = [
    ]
    private_ip             = "10.0.0.3"
    skip_source_dest_check = "true"
    subnet_id              = oci_core_subnet.export_Public-Subnet-fgtvm.id
    #vlan_id = <<Optional value not found in discovery>>
  }
  #dedicated_vm_host_id = <<Optional value not found in discovery>>
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azure_economieqc/apiroyer@economieqc.onmicrosoft.com"
    "Oracle-Tags.CreatedOn" = "2021-11-04T01:06:42.914Z"
  }
  display_name = "FORTI-MASTER1"
  extended_metadata = {
  }
  fault_domain = "FAULT-DOMAIN-2"
  freeform_tags = {
  }
  instance_options {
    are_legacy_imds_endpoints_disabled = "false"
  }
  #ipxe_script = <<Optional value not found in discovery>>
  #is_pv_encryption_in_transit_enabled = <<Optional value not found in discovery>>
  launch_options {
    boot_volume_type                    = "PARAVIRTUALIZED"
    firmware                            = "BIOS"
    is_consistent_volume_naming_enabled = "false"
    is_pv_encryption_in_transit_enabled = "false"
    network_type                        = "VFIO"
    remote_data_volume_type             = "PARAVIRTUALIZED"
  }
  metadata = {
    "ssh_authorized_keys" = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAjKT33iVm2sVkLlkNCoVAgh6xu3KCGv2lfXIoQ8NraVtZd/XWJY8p/3dtl90XICF8k0DAPfqiQlx7mylp9rgpIzUPrzc/EXWdi5OlDliDtpEQnRLHIYwEChBWzsN2iB4Z9j5cQxzJuFBwo3KtaVxVSm3U3lYCMq/AFN+7zkRq4n8ABLPZ09kPRA17iiuDSGePZHMD+LgYZIjCsuOaHJzG+DWQQa3PgEbQ6WCgcdm8ewZ9byOhlBu/xlfW9ZSTnv6J8A24syAOtVHrKS/HKNv++bCqPhkhy96GUyGDeE4Tc70DkPSjRFQbuH5n5Rwu3MYHEeQPpmiGNqZtpMiLqJHX ssh-key-2021-11-04"
  }
  #preserve_boot_volume = <<Optional value not found in discovery>>
  shape = "VM.Standard.E3.Flex"
  shape_config {
    baseline_ocpu_utilization = "BASELINE_1_1"
    memory_in_gbs             = "64"
    ocpus                     = "4"
  }
  source_details {
    #boot_volume_size_in_gbs = <<Optional value not found in discovery>>
    #kms_key_id = <<Optional value not found in discovery>>
    source_id   = var.export_FORTI-SLAVEB_source_image_id
    source_type = "image"
  }
  state = "RUNNING"
}

resource oci_core_instance export_FORTI-SLAVEB {
  agent_config {
    are_all_plugins_disabled = "false"
    is_management_disabled   = "false"
    is_monitoring_disabled   = "false"
    plugins_config {
      desired_state = "DISABLED"
      name          = "Vulnerability Scanning"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Oracle Autonomous Linux"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "OS Management Service Agent"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Management Agent"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "Custom Logs Monitoring"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "Compute Instance Run Command"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "Compute Instance Monitoring"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Block Volume Management"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Bastion"
    }
  }
  #async = <<Optional value not found in discovery>>
  availability_config {
    #is_live_migration_preferred = <<Optional value not found in discovery>>
    recovery_action = "RESTORE_INSTANCE"
  }
  availability_domain = data.oci_identity_availability_domain.export_IzXN-CA-TORONTO-1-AD-1.name
  #capacity_reservation_id = <<Optional value not found in discovery>>
  compartment_id = var.compartment_ocid
  create_vnic_details {
    #assign_private_dns_record = <<Optional value not found in discovery>>
    assign_public_ip = "true"
    defined_tags = {
      "Oracle-Tags.CreatedBy" = "azure_economieqc/apiroyer@economieqc.onmicrosoft.com"
      "Oracle-Tags.CreatedOn" = "2021-11-04T01:08:23.527Z"
    }
    display_name = "PORT1"
    freeform_tags = {
    }
    hostname_label = "forti-slaveb"
    nsg_ids = [
    ]
    private_ip             = "10.0.0.4"
    skip_source_dest_check = "true"
    subnet_id              = oci_core_subnet.export_Public-Subnet-fgtvm.id
    #vlan_id = <<Optional value not found in discovery>>
  }
  #dedicated_vm_host_id = <<Optional value not found in discovery>>
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azure_economieqc/apiroyer@economieqc.onmicrosoft.com"
    "Oracle-Tags.CreatedOn" = "2021-11-04T01:08:23.386Z"
  }
  display_name = "FORTI-SLAVEB"
  extended_metadata = {
  }
  fault_domain = "FAULT-DOMAIN-2"
  freeform_tags = {
  }
  instance_options {
    are_legacy_imds_endpoints_disabled = "false"
  }
  #ipxe_script = <<Optional value not found in discovery>>
  #is_pv_encryption_in_transit_enabled = <<Optional value not found in discovery>>
  launch_options {
    boot_volume_type                    = "PARAVIRTUALIZED"
    firmware                            = "BIOS"
    is_consistent_volume_naming_enabled = "false"
    is_pv_encryption_in_transit_enabled = "false"
    network_type                        = "VFIO"
    remote_data_volume_type             = "PARAVIRTUALIZED"
  }
  metadata = {
    "ssh_authorized_keys" = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDLqxRn02iCY937G8+4dnFkrF7Gp9ke+rCQLHVATGhKcWus8LPKV6L96zbblP54T0BJrYbUyOnuK9XHStAxBV+RFue0Uk3JGyBguYLkosJXy5z74gFEF4htW+tG/dKQ3gJg0bw0al4PVNNumG6CU9V6CcteTyvCK7VD6qm+8KthcDjnRMdcYrnawAwLBPc2i0uRK4gvZhCKIG8z+oTnnUKg4BmvfFfz8rTW63KDC/aC2BL6yxuW0b357AqvzqL12GqDOeWHWnXi/Q0ux9g4JMRyLSbt4cOJ3kUeRIGuwW/2GHfFi+zVY5vqDeKeVfnNSFs92eMEijX323VPWj+1kIjd ssh-key-2021-11-04"
  }
  #preserve_boot_volume = <<Optional value not found in discovery>>
  shape = "VM.Standard.E3.Flex"
  shape_config {
    baseline_ocpu_utilization = "BASELINE_1_1"
    memory_in_gbs             = "64"
    ocpus                     = "4"
  }
  source_details {
    #boot_volume_size_in_gbs = <<Optional value not found in discovery>>
    #kms_key_id = <<Optional value not found in discovery>>
    source_id   = var.export_FORTI-SLAVEB_source_image_id
    source_type = "image"
  }
  state = "STOPPED"
}

resource oci_core_vnic_attachment export_vnicattachment20211104012810 {
  create_vnic_details {
    #assign_private_dns_record = <<Optional value not found in discovery>>
    assign_public_ip = "true"
    defined_tags = {
      "Oracle-Tags.CreatedBy" = "azure_economieqc/apiroyer@economieqc.onmicrosoft.com"
      "Oracle-Tags.CreatedOn" = "2021-11-04T01:28:10.263Z"
    }
    display_name = "PORT2"
    freeform_tags = {
    }
    #hostname_label = <<Optional value not found in discovery>>
    nsg_ids = [
    ]
    private_ip             = "10.0.12.4"
    skip_source_dest_check = "true"
    subnet_id              = oci_core_subnet.export_untrust-public.id
    #vlan_id = <<Optional value not found in discovery>>
  }
  display_name = "vnicattachment20211104012810"
  instance_id  = oci_core_instance.export_FORTI-MASTER1.id
  nic_index    = "0"
}

resource oci_core_vnic_attachment export_vnicattachment20211104014002 {
  create_vnic_details {
    #assign_private_dns_record = <<Optional value not found in discovery>>
    assign_public_ip = "false"
    defined_tags = {
      "Oracle-Tags.CreatedBy" = "azure_economieqc/apiroyer@economieqc.onmicrosoft.com"
      "Oracle-Tags.CreatedOn" = "2021-11-04T01:40:02.574Z"
    }
    display_name = "PORT4"
    freeform_tags = {
    }
    #hostname_label = <<Optional value not found in discovery>>
    nsg_ids = [
    ]
    private_ip             = "10.0.10.3"
    skip_source_dest_check = "false"
    subnet_id              = oci_core_subnet.export_heartbeat.id
    #vlan_id = <<Optional value not found in discovery>>
  }
  display_name = "vnicattachment20211104014002"
  instance_id  = oci_core_instance.export_FORTI-MASTER1.id
  nic_index    = "0"
}

resource oci_core_vnic_attachment export_vnicattachment20211104013710 {
  create_vnic_details {
    #assign_private_dns_record = <<Optional value not found in discovery>>
    assign_public_ip = "false"
    defined_tags = {
      "Oracle-Tags.CreatedBy" = "azure_economieqc/apiroyer@economieqc.onmicrosoft.com"
      "Oracle-Tags.CreatedOn" = "2021-11-04T01:37:10.810Z"
    }
    display_name = "PORT3"
    freeform_tags = {
    }
    #hostname_label = <<Optional value not found in discovery>>
    nsg_ids = [
    ]
    private_ip             = "10.0.8.3"
    skip_source_dest_check = "true"
    subnet_id              = oci_core_subnet.export_trust-private.id
    #vlan_id = <<Optional value not found in discovery>>
  }
  display_name = "vnicattachment20211104013710"
  instance_id  = oci_core_instance.export_FORTI-MASTER1.id
  nic_index    = "0"
}

resource oci_core_vnic_attachment export_vnicattachment20211104014906 {
  create_vnic_details {
    #assign_private_dns_record = <<Optional value not found in discovery>>
    assign_public_ip = "false"
    defined_tags = {
      "Oracle-Tags.CreatedBy" = "azure_economieqc/apiroyer@economieqc.onmicrosoft.com"
      "Oracle-Tags.CreatedOn" = "2021-11-04T01:49:06.135Z"
    }
    display_name = "PORT3"
    freeform_tags = {
    }
    #hostname_label = <<Optional value not found in discovery>>
    nsg_ids = [
    ]
    private_ip             = "10.0.8.2"
    skip_source_dest_check = "true"
    subnet_id              = oci_core_subnet.export_trust-private.id
    #vlan_id = <<Optional value not found in discovery>>
  }
  display_name = "vnicattachment20211104014906"
  instance_id  = oci_core_instance.export_FORTI-SLAVEB.id
  nic_index    = "0"
}

resource oci_core_vnic_attachment export_vnicattachment20211104014938 {
  create_vnic_details {
    #assign_private_dns_record = <<Optional value not found in discovery>>
    assign_public_ip = "false"
    defined_tags = {
      "Oracle-Tags.CreatedBy" = "azure_economieqc/apiroyer@economieqc.onmicrosoft.com"
      "Oracle-Tags.CreatedOn" = "2021-11-04T01:49:38.438Z"
    }
    display_name = "PORT4"
    freeform_tags = {
    }
    #hostname_label = <<Optional value not found in discovery>>
    nsg_ids = [
    ]
    private_ip             = "10.0.10.4"
    skip_source_dest_check = "false"
    subnet_id              = oci_core_subnet.export_heartbeat.id
    #vlan_id = <<Optional value not found in discovery>>
  }
  display_name = "vnicattachment20211104014938"
  instance_id  = oci_core_instance.export_FORTI-SLAVEB.id
  nic_index    = "0"
}

resource oci_core_vnic_attachment export_vnicattachment20211104014736 {
  create_vnic_details {
    #assign_private_dns_record = <<Optional value not found in discovery>>
    assign_public_ip = "false"
    defined_tags = {
      "Oracle-Tags.CreatedBy" = "azure_economieqc/apiroyer@economieqc.onmicrosoft.com"
      "Oracle-Tags.CreatedOn" = "2021-11-04T01:47:36.800Z"
    }
    display_name = "PORT2"
    freeform_tags = {
    }
    #hostname_label = <<Optional value not found in discovery>>
    nsg_ids = [
    ]
    private_ip             = "10.0.12.2"
    skip_source_dest_check = "true"
    subnet_id              = oci_core_subnet.export_untrust-public.id
    #vlan_id = <<Optional value not found in discovery>>
  }
  display_name = "vnicattachment20211104014736"
  instance_id  = oci_core_instance.export_FORTI-SLAVEB.id
  nic_index    = "0"
}

resource oci_core_internet_gateway export_Internet-Gateway-fgtvm {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azure_economieqc/apiroyer@economieqc.onmicrosoft.com"
    "Oracle-Tags.CreatedOn" = "2021-11-03T18:11:33.599Z"
  }
  display_name = "Internet Gateway-fgtvm"
  enabled      = "true"
  freeform_tags = {
    "VCN" = "VCN-2021-11-03T18:09:57"
  }
  vcn_id = oci_core_vcn.export_fgtvm.id
}

resource oci_core_public_ip export_pip1-forti1-port2 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azure_economieqc/apiroyer@economieqc.onmicrosoft.com"
    "Oracle-Tags.CreatedOn" = "2021-11-04T01:30:42.937Z"
  }
  display_name = "pip1-forti1-port2"
  freeform_tags = {
  }
  lifetime      = "RESERVED"
  private_ip_id = oci_core_private_ip.export_privateip20211104013042.id
  #public_ip_pool_id = <<Optional value not found in discovery>>
}

resource oci_core_public_ip export_pip2-forti1-port2 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azure_economieqc/apiroyer@economieqc.onmicrosoft.com"
    "Oracle-Tags.CreatedOn" = "2021-11-04T01:31:16.148Z"
  }
  display_name = "pip2-forti1-port2"
  freeform_tags = {
  }
  lifetime      = "RESERVED"
  private_ip_id = oci_core_private_ip.export_privateip20211104013115.id
  #public_ip_pool_id = <<Optional value not found in discovery>>
}

resource oci_core_service_gateway export_Service-Gateway-fgtvm {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azure_economieqc/apiroyer@economieqc.onmicrosoft.com"
    "Oracle-Tags.CreatedOn" = "2021-11-03T18:11:33.619Z"
  }
  display_name = "Service Gateway-fgtvm"
  freeform_tags = {
    "VCN" = "VCN-2021-11-03T18:09:57"
  }
  #route_table_id = <<Optional value not found in discovery>>
  services {
    service_id = "ocid1.service.oc1.ca-toronto-1.aaaaaaaaxwhdaheitj3qvugait3k4cqnqt6d76dlhxl3nv3dof6abuu4xhga"
  }
  vcn_id = oci_core_vcn.export_fgtvm.id
}

resource oci_core_subnet export_heartbeat {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.10.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azure_economieqc/apiroyer@economieqc.onmicrosoft.com"
    "Oracle-Tags.CreatedOn" = "2021-11-03T19:00:06.966Z"
  }
  dhcp_options_id = oci_core_vcn.export_fgtvm.default_dhcp_options_id
  display_name    = "heartbeat"
  dns_label       = "heartbeat"
  freeform_tags = {
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  prohibit_internet_ingress  = "true"
  prohibit_public_ip_on_vnic = "true"
  route_table_id             = oci_core_vcn.export_fgtvm.default_route_table_id
  security_list_ids = [
    oci_core_vcn.export_fgtvm.default_security_list_id,
  ]
  vcn_id = oci_core_vcn.export_fgtvm.id
}

resource oci_core_subnet export_trust-private {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.8.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azure_economieqc/apiroyer@economieqc.onmicrosoft.com"
    "Oracle-Tags.CreatedOn" = "2021-11-03T18:59:29.069Z"
  }
  dhcp_options_id = oci_core_vcn.export_fgtvm.default_dhcp_options_id
  display_name    = "trust private"
  dns_label       = "trustprivate"
  freeform_tags = {
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  prohibit_internet_ingress  = "true"
  prohibit_public_ip_on_vnic = "true"
  route_table_id             = oci_core_vcn.export_fgtvm.default_route_table_id
  security_list_ids = [
    oci_core_vcn.export_fgtvm.default_security_list_id,
  ]
  vcn_id = oci_core_vcn.export_fgtvm.id
}

resource oci_core_subnet export_untrust-public {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.12.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azure_economieqc/apiroyer@economieqc.onmicrosoft.com"
    "Oracle-Tags.CreatedOn" = "2021-11-03T18:58:24.866Z"
  }
  dhcp_options_id = oci_core_vcn.export_fgtvm.default_dhcp_options_id
  display_name    = "untrust public"
  dns_label       = "untrustpublic"
  freeform_tags = {
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  prohibit_internet_ingress  = "false"
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = oci_core_vcn.export_fgtvm.default_route_table_id
  security_list_ids = [
    oci_core_vcn.export_fgtvm.default_security_list_id,
  ]
  vcn_id = oci_core_vcn.export_fgtvm.id
}

resource oci_core_subnet export_Public-Subnet-fgtvm {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.0.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azure_economieqc/apiroyer@economieqc.onmicrosoft.com"
    "Oracle-Tags.CreatedOn" = "2021-11-03T18:11:33.548Z"
  }
  dhcp_options_id = oci_core_vcn.export_fgtvm.default_dhcp_options_id
  display_name    = "Public Subnet-fgtvm"
  dns_label       = "sub11031811260"
  freeform_tags = {
    "VCN" = "VCN-2021-11-03T18:09:57"
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  prohibit_internet_ingress  = "false"
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = oci_core_vcn.export_fgtvm.default_route_table_id
  security_list_ids = [
    oci_core_vcn.export_fgtvm.default_security_list_id,
  ]
  vcn_id = oci_core_vcn.export_fgtvm.id
}

resource oci_core_private_ip export_PORT4 {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azure_economieqc/apiroyer@economieqc.onmicrosoft.com"
    "Oracle-Tags.CreatedOn" = "2021-11-04T01:40:02.574Z"
  }
  display_name = "PORT4"
  freeform_tags = {
  }
  #hostname_label = <<Optional value not found in discovery>>
  ip_address = "10.0.10.3"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.ca-toronto-1.ab2g6ljrvdihv4linvjmhujeevpnxxkm5gwa5mndpngirhzf4w3tpmhpdona"
}

resource oci_core_private_ip export_PORT4_1 {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azure_economieqc/apiroyer@economieqc.onmicrosoft.com"
    "Oracle-Tags.CreatedOn" = "2021-11-04T01:49:38.438Z"
  }
  display_name = "PORT4"
  freeform_tags = {
  }
  #hostname_label = <<Optional value not found in discovery>>
  ip_address = "10.0.10.4"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.ca-toronto-1.ab2g6ljrebs6pohoyfjxniqpmr4s2cgmolcxw3cxpev5ubxmqs27h7uxbkra"
}

resource oci_core_private_ip export_PORT3 {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azure_economieqc/apiroyer@economieqc.onmicrosoft.com"
    "Oracle-Tags.CreatedOn" = "2021-11-04T01:49:06.135Z"
  }
  display_name = "PORT3"
  freeform_tags = {
  }
  #hostname_label = <<Optional value not found in discovery>>
  ip_address = "10.0.8.2"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.ca-toronto-1.ab2g6ljrmfq5jmooooudb3h7us2sdtpzrkkr2kkjmxxfuyx4wnc726e4lqia"
}

resource oci_core_private_ip export_PORT3_1 {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azure_economieqc/apiroyer@economieqc.onmicrosoft.com"
    "Oracle-Tags.CreatedOn" = "2021-11-04T01:37:10.810Z"
  }
  display_name = "PORT3"
  freeform_tags = {
  }
  #hostname_label = <<Optional value not found in discovery>>
  ip_address = "10.0.8.3"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.ca-toronto-1.ab2g6ljrewgiuf65wdyswp7mixjq3vrykhe5wy2qhsjz7yeayg4jyqh5jehq"
}

resource oci_core_private_ip export_privateip20211104013752 {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azure_economieqc/apiroyer@economieqc.onmicrosoft.com"
    "Oracle-Tags.CreatedOn" = "2021-11-04T01:37:51.959Z"
  }
  display_name = "privateip20211104013752"
  freeform_tags = {
  }
  #hostname_label = <<Optional value not found in discovery>>
  ip_address = "10.0.8.10"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.ca-toronto-1.ab2g6ljrewgiuf65wdyswp7mixjq3vrykhe5wy2qhsjz7yeayg4jyqh5jehq"
}

resource oci_core_private_ip export_PORT2 {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azure_economieqc/apiroyer@economieqc.onmicrosoft.com"
    "Oracle-Tags.CreatedOn" = "2021-11-04T01:47:36.800Z"
  }
  display_name = "PORT2"
  freeform_tags = {
  }
  #hostname_label = <<Optional value not found in discovery>>
  ip_address = "10.0.12.2"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.ca-toronto-1.ab2g6ljreybn7lqede7il6diuqsw4sochpwvsqfcr3xybqt6syxo2ebknama"
}

resource oci_core_private_ip export_privateip20211104013042 {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azure_economieqc/apiroyer@economieqc.onmicrosoft.com"
    "Oracle-Tags.CreatedOn" = "2021-11-04T01:30:42.262Z"
  }
  display_name = "privateip20211104013042"
  freeform_tags = {
  }
  #hostname_label = <<Optional value not found in discovery>>
  ip_address = "10.0.12.3"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.ca-toronto-1.ab2g6ljr75wvtbtewwaljmps6tw5rerdp4kv2ibwlcm426xbqyebfxj2wlaa"
}

resource oci_core_private_ip export_PORT2_1 {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azure_economieqc/apiroyer@economieqc.onmicrosoft.com"
    "Oracle-Tags.CreatedOn" = "2021-11-04T01:28:10.263Z"
  }
  display_name = "PORT2"
  freeform_tags = {
  }
  #hostname_label = <<Optional value not found in discovery>>
  ip_address = "10.0.12.4"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.ca-toronto-1.ab2g6ljr75wvtbtewwaljmps6tw5rerdp4kv2ibwlcm426xbqyebfxj2wlaa"
}

resource oci_core_private_ip export_privateip20211104013115 {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azure_economieqc/apiroyer@economieqc.onmicrosoft.com"
    "Oracle-Tags.CreatedOn" = "2021-11-04T01:31:15.449Z"
  }
  display_name = "privateip20211104013115"
  freeform_tags = {
  }
  #hostname_label = <<Optional value not found in discovery>>
  ip_address = "10.0.12.5"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.ca-toronto-1.ab2g6ljr75wvtbtewwaljmps6tw5rerdp4kv2ibwlcm426xbqyebfxj2wlaa"
}

resource oci_core_private_ip export_PORT1 {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azure_economieqc/apiroyer@economieqc.onmicrosoft.com"
    "Oracle-Tags.CreatedOn" = "2021-11-04T01:06:43.031Z"
  }
  display_name = "PORT1"
  freeform_tags = {
  }
  hostname_label = "forti-master1"
  ip_address     = "10.0.0.3"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.ca-toronto-1.ab2g6ljrrw7helavu4md7aeubo7aakyjzohyfxcfuknn2qxdsi4bgy2j63wq"
}

resource oci_core_private_ip export_PORT1_1 {
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azure_economieqc/apiroyer@economieqc.onmicrosoft.com"
    "Oracle-Tags.CreatedOn" = "2021-11-04T01:08:23.527Z"
  }
  display_name = "PORT1"
  freeform_tags = {
  }
  hostname_label = "forti-slaveb"
  ip_address     = "10.0.0.4"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.ca-toronto-1.ab2g6ljrcyqmdr7fjobe3f6pvy2rmevxdcwytpzsgtua3fy3iaej3bm7daqq"
}

resource oci_core_vcn export_fgtvm {
  #cidr_block = <<Optional value not found in discovery>>
  cidr_blocks = [
    "10.0.0.0/16",
  ]
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azure_economieqc/apiroyer@economieqc.onmicrosoft.com"
    "Oracle-Tags.CreatedOn" = "2021-11-03T18:11:32.749Z"
  }
  display_name = "fgtvm"
  dns_label    = "fgtvm"
  freeform_tags = {
    "VCN" = "VCN-2021-11-03T18:09:57"
  }
  #is_ipv6enabled = <<Optional value not found in discovery>>
}

resource oci_core_default_dhcp_options export_Default-DHCP-Options-for-fgtvm {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azure_economieqc/apiroyer@economieqc.onmicrosoft.com"
    "Oracle-Tags.CreatedOn" = "2021-11-03T18:11:32.749Z"
  }
  display_name     = "Default DHCP Options for fgtvm"
  domain_name_type = "CUSTOM_DOMAIN"
  freeform_tags = {
    "VCN" = "VCN-2021-11-03T18:09:57"
  }
  manage_default_resource_id = oci_core_vcn.export_fgtvm.default_dhcp_options_id
  options {
    custom_dns_servers = [
    ]
    #search_domain_names = <<Optional value not found in discovery>>
    server_type = "VcnLocalPlusInternet"
    type        = "DomainNameServer"
  }
  options {
    #custom_dns_servers = <<Optional value not found in discovery>>
    search_domain_names = [
      "fgtvm.oraclevcn.com",
    ]
    #server_type = <<Optional value not found in discovery>>
    type = "SearchDomain"
  }
}

resource oci_core_nat_gateway export_NAT-Gateway-fgtvm {
  block_traffic  = "false"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azure_economieqc/apiroyer@economieqc.onmicrosoft.com"
    "Oracle-Tags.CreatedOn" = "2021-11-03T18:11:33.570Z"
  }
  display_name = "NAT Gateway-fgtvm"
  freeform_tags = {
    "VCN" = "VCN-2021-11-03T18:09:57"
  }
  public_ip_id = "ocid1.publicip.oc1.ca-toronto-1.aaaaaaaaa2e3ko5bfjgzj3dngxvtb34a73gkuz6vnb6xuq4a4xilc2gvmz3a"
  vcn_id       = oci_core_vcn.export_fgtvm.id
}

resource oci_core_route_table export_Route-Table-for-Private-Subnet-fgtvm {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azure_economieqc/apiroyer@economieqc.onmicrosoft.com"
    "Oracle-Tags.CreatedOn" = "2021-11-03T18:11:33.846Z"
  }
  display_name = "Route Table for Private Subnet-fgtvm"
  freeform_tags = {
    "VCN" = "VCN-2021-11-03T18:09:57"
  }
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_nat_gateway.export_NAT-Gateway-fgtvm.id
  }
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "all-yyz-services-in-oracle-services-network"
    destination_type  = "SERVICE_CIDR_BLOCK"
    network_entity_id = oci_core_service_gateway.export_Service-Gateway-fgtvm.id
  }
  vcn_id = oci_core_vcn.export_fgtvm.id
}

resource oci_core_default_route_table export_Default-Route-Table-for-fgtvm {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azure_economieqc/apiroyer@economieqc.onmicrosoft.com"
    "Oracle-Tags.CreatedOn" = "2021-11-03T18:11:32.749Z"
  }
  display_name = "Default Route Table for fgtvm"
  freeform_tags = {
    "VCN" = "VCN-2021-11-03T18:09:57"
  }
  manage_default_resource_id = oci_core_vcn.export_fgtvm.default_route_table_id
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.export_Internet-Gateway-fgtvm.id
  }
}

resource oci_core_security_list export_Security-List-for-Private-Subnet-fgtvm {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azure_economieqc/apiroyer@economieqc.onmicrosoft.com"
    "Oracle-Tags.CreatedOn" = "2021-11-03T18:11:33.909Z"
  }
  display_name = "Security List for Private Subnet-fgtvm"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
    "VCN" = "VCN-2021-11-03T18:09:57"
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  vcn_id = oci_core_vcn.export_fgtvm.id
}

resource oci_core_default_security_list export_Default-Security-List-for-fgtvm {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "azure_economieqc/apiroyer@economieqc.onmicrosoft.com"
    "Oracle-Tags.CreatedOn" = "2021-11-03T18:11:32.749Z"
  }
  display_name = "Default Security List for fgtvm"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
    "VCN" = "VCN-2021-11-03T18:09:57"
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "443"
      min = "443"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  manage_default_resource_id = oci_core_vcn.export_fgtvm.default_security_list_id
}

