## This configuration was generated by terraform-provider-oci

resource oci_marketplace_accepted_agreement export_acceptedAgreement-50511633ocid1-saml2idp-oc1-aaaaaaaaeia2keiqzq5oaskyhinhr2d345zxnxfxghme3fffwtvwxqmrxyfq-apiroyer-economieqc-onmicrosoft-com {
  agreement_id   = "50511633"
  compartment_id = var.compartment_ocid
  defined_tags = {
  }
  display_name = "acceptedAgreement-50511633ocid1.saml2idp.oc1..aaaaaaaaeia2keiqzq5oaskyhinhr2d345zxnxfxghme3fffwtvwxqmrxyfq/apiroyer@economieqc.onmicrosoft.com"
  freeform_tags = {
  }
  listing_id      = "42416321"
  package_version = "7.0.2 SR-IOV Paravirtualized Mode"
  signature       = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [signature]
  }
}

resource oci_marketplace_accepted_agreement export_acceptedAgreement-piiocid1-saml2idp-oc1-aaaaaaaaeia2keiqzq5oaskyhinhr2d345zxnxfxghme3fffwtvwxqmrxyfq-apiroyer-economieqc-onmicrosoft-com {
  agreement_id   = "pii"
  compartment_id = var.compartment_ocid
  defined_tags = {
  }
  display_name = "acceptedAgreement-piiocid1.saml2idp.oc1..aaaaaaaaeia2keiqzq5oaskyhinhr2d345zxnxfxghme3fffwtvwxqmrxyfq/apiroyer@economieqc.onmicrosoft.com"
  freeform_tags = {
  }
  listing_id      = "42416321"
  package_version = "7.0.2 SR-IOV Paravirtualized Mode"
  signature       = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [signature]
  }
}

resource oci_marketplace_accepted_agreement export_acceptedAgreement-47781111ocid1-saml2idp-oc1-aaaaaaaaeia2keiqzq5oaskyhinhr2d345zxnxfxghme3fffwtvwxqmrxyfq-apiroyer-economieqc-onmicrosoft-com {
  agreement_id   = "47781111"
  compartment_id = var.compartment_ocid
  defined_tags = {
  }
  display_name = "acceptedAgreement-47781111ocid1.saml2idp.oc1..aaaaaaaaeia2keiqzq5oaskyhinhr2d345zxnxfxghme3fffwtvwxqmrxyfq/apiroyer@economieqc.onmicrosoft.com"
  freeform_tags = {
  }
  listing_id      = "42416321"
  package_version = "7.0.2 SR-IOV Paravirtualized Mode"
  signature       = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [signature]
  }
}

